### ISSUE TITLE
列表滚动时，倒计时全都停了，这。。。

### ISSUE THREAD

**Issue by xiaohuiCoding** [YasinZhou/CellTimerDemo#1]

**Comment by YasinZhou** [comment]
那是因为timer添加在runloop中Mode的是默认的，如果你有需要可以添加下面的代码
`[[NSRunLoop mainRunLoop] addTimer:timer forMode:NSRunLoopCommonModes];`

**Comment by YasinZhou** [comment]
`[[NSRunLoop currentRunLoop] addTimer:self.timer forMode:NSRunLoopCommonModes];`

这个也可以，看你的需要吧
